name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

  
  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull kasunkalharabamunuarachchi123/my-react-app:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 80:3000 --name my-react-app kasunkalharabamunuarachchi123/my-react-app:latest
   